[package]
name = "mdvim"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "^0.29"
crossterm = "0.29.0"
pulldown-cmark = "0.13.0"
unicode-width = "0.2.0"
syntect = "5.3.0"
once_cell = "1.21.3"
